### PR TITLE
Secure PKRU during thread startup

### LINKED ISSUE #257: Thread startup saves PKRU in spillable register across function calls
See `ALLOCATE_COMPARTMENT_STACK_AND_SETUP_TLS`. For each compartment, we save PKRU in `r12d`, change PKRU to the pkey for compartment, call `init_tls_N` for that compartment, then restore the PKRU from `r12d`.

The latter step can end up reading the wrong value if r12 is spilled to the stack and another thread in the same compartment writes to that memory before the register is unspilled. This can change what PKRU value the thread ends up running its main function with. The PKRU is then used to decide which compartment stack gets used for the thread, so a PKRU for the wrong compartment can/will not be noticed. A PKRU value that has pkeys for multiple compartments will get `NULL` back from `ia2_stackptr_for_pkru`, which will result in a null dereference and DoS, but one for another compartment will not.

### PR DESCRIPTION
**Pull request by rinon**
Rather than saving and restoring the PKRU from a register when allocating and securing thread stacks, we branch on the initial value to one of a set of duplicated initialization routines, each of which hard-codes the PKRU value to restore after initialization.

Fixes #257

### CODE REVIEW

File: runtime/libia2/include/ia2_internal.h [hunk 1]
```diff
@@ -210,19 +214,13 @@ asm(".macro movz_shifted_tag_x18 tag\n"
         "mov ia2_stackptr_" #i "@GOTTPOFF(%%rip),%%r11\n"                      \
         /* check that stack pointer holds NULL */                              \
         "cmpq $0x0,%%fs:(%%r11)\n"                                             \
-        "je .Lfresh_init" #i "\n"                                              \
+        "je .Lfresh_init%=" #i "\n"                                            \
```
Comment (fw-immunant) [inline runtime/libia2/include/ia2_internal.h:217]: What does this `%=` syntax do?

Comment (rinon) [reply runtime/libia2/include/ia2_internal.h:217]: Creates a fresh unique label (this asm block is now duplicated and labels are a global namespace).

File: runtime/libia2/include/ia2_internal.h [hunk 2]
```diff
@@ -40,29 +47,46 @@ struct dl_phdr_info;
...
+#define REPEATB14(fn, basefn, ...) fn(14, ##__VA_ARGS__) REPEATB13(fn, basefn, ##__VA_ARGS__)
+#define REPEATB15(fn, basefn, ...) fn(15, ##__VA_ARGS__) REPEATB14(fn, basefn, ##__VA_ARGS__)
 /* clang-format on */
 
 /* Macro to repeatedly apply a function or function-like macro `fn` a given
 number of times, passing the index to each invocation. The passed index `n` is
 first, followed by n-1 and so on. For the base case of 0, `basefn` is applied
 instead of `fn`. */
-#define REPEATB(n, fn, basefn) REPEATB##n(fn, basefn)
+#define REPEATA(n, fn, basefn, ...) REPEATA##n(fn, basefn, ##__VA_ARGS__)
```
Comment (fw-immunant) [inline runtime/libia2/include/ia2_internal.h:88]: Can you document this? As a historical note, the `REPEATB` name came from "**REPEAT** this macro application _n_ times, with a different **B**ase case". What's the intuition for the `REPEATA` name and how is it used? Is it just expanding in the opposite order to give an ascending sequence?

File: runtime/libia2/include/ia2_internal.h (hunk 1 above)
Comment (fw-immunant) [reply runtime/libia2/include/ia2_internal.h:240]: This might be worth commenting because I couldn't find any docs for this syntax in a cursory google search.

Comment (fw-immunant) [reply runtime/libia2/include/ia2_internal.h:240]: Ohh, this is an inline ASM thing rather than an assembler feature: https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#Special-format-strings

**Review by fw-immunant — APPROVED** [review]
Semantically LGTM, a couple non-functional nits.

**Comment by rinon** [comment]
@fw-immunant how about `REPEATB_REV()`?

**Comment by fw-immunant** [comment]
Thanks! Feel free to merge.
