### PR TITLE
Fix struct copying for structs with an unaligned size

### LINKED ISSUE #365: Structs test fails on Arch (LLVM 18)
```
[----] ./tests/structs/main.c:143: Assertion Failed
[----]
[----]   The expression s.i1 == 1 + 100 + 8043 / 2 is false.
[----]
[FAIL] structs::main: (0.00s)
[====] Synthesis: Tested: 1 | Passing: 0 | Failing: 1 | Crashing: 0
```

### PR DESCRIPTION
**Pull request by rinon**
Clang started packing structs immediately after
stack arguments, but we used to copy memory
arguments as 8-byte chunks. Instead, copy only up
to the size of the struct argument to avoid
overwriting other bytes above it on the stack.

Fixes #365

### CODE REVIEW

File: tools/rewriter/GenCallAsm.cpp [hunk 1]
```diff
@@ -184,6 +189,19 @@ static void emit_reg_pop(AsmWriter &aw, const ParamLocation &loc) {
   }
 }
 
+// Emit code to copy `byte_count` bytes from `src` to `dst` using `scratch` as a
+// temporary register.
+static void emit_memcpy(AsmWriter &aw, unsigned byte_count, const std::string &dst,
```
Comment (fw-immunant) [inline tools/rewriter/GenCallAsm.cpp:194]: It's probably worth calling out that this copies a rounded-up multiple of 8-byte chunks rather than `byte_count` exactly.

File: tools/rewriter/GenCallAsm.cpp [hunk 2]
```diff
@@ -391,27 +409,31 @@ static void emit_copy_args(AsmWriter &aw, size_t stack_return_size, size_t stack
...
-        // The index into the caller's stack is backwards since pushq will copy to
-        // the compartment's stack from the highest addresses to the lowest.
-        add_asm_line(aw,
-                     "pushq " + std::to_string(caller_stack_size - i) + "(%rax)");
-      }
+      // We must take the preserved registers we pushed on the caller's stack
+      // into account (including rbp and the return address) when determining
+      // the location of the stack args.
+      size_t offset = (preserved_registers.size() + 2) * 8;
+      emit_memcpy(aw, stack_arg_size, "rsp", "rax", "r10", offset);
```
Comment (fw-immunant) [inline tools/rewriter/GenCallAsm.cpp:425]: Don't split up construction and use of `expr`.

Is it preferable to use `mov`s and a separate modification of `rsp` here as opposed to the `push`es used before, or is there another reason to change this?

If we do use `mov` and a temporary, we should probably reuse `r12` which we just clobbered.

File: tools/rewriter/GenCallAsm.cpp [hunk 3]
```diff
@@ -391,27 +409,31 @@ static void emit_copy_args(AsmWriter &aw, size_t stack_return_size, size_t stack
...
+      //   // We must take the preserved registers we pushed on the caller's stack
+      //   // into account (including rbp) when determining the location of the stack
+      //   // args
+      //   size_t caller_stack_size =
+      //       stack_arg_size + ((preserved_registers.size() + 1) * 8);
+      //   // The index into the caller's stack is backwards since pushq will copy to
+      //   // the compartment's stack from the highest addresses to the lowest.
+      //   add_asm_line(aw,
+      //                "pushq " + std::to_string(caller_stack_size - i) + "(%rax)");
+      // }
```
Comment (fw-immunant) [inline tools/rewriter/GenCallAsm.cpp:436]: No need to leave this around in a comment.

File: tools/rewriter/GenCallAsm.cpp [hunk 4]
```diff
@@ -446,12 +468,12 @@ static void emit_set_pkru(AsmWriter &aw, uint32_t target_pkey, Arch arch) {
...
 }
 
-static void emit_free_stack_space(AsmWriter &aw, size_t stack_arg_size, int stack_alignment, Arch arch) {
+static void emit_free_stack_space(AsmWriter &aw, size_t stack_arg_size, size_t stack_arg_padding, int stack_alignment, Arch arch) {
   if (arch == Arch::X86) {
     // Free stack space used for stack args on the target stack
     if (stack_arg_size > 0) {
       add_comment_line(aw, "Free stack space used for stack args");
-      add_asm_line(aw, "addq $"s + std::to_string(stack_arg_size) + ", %rsp");
+      add_asm_line(aw, "addq $"s + std::to_string(stack_arg_size + stack_arg_padding) + ", %rsp");
```
Comment (fw-immunant) [inline tools/rewriter/GenCallAsm.cpp:476]: Is the padding here doing something other than rounding the arg size up to the passed alignment?

File: tools/rewriter/GenCallAsm.cpp [hunk 5]
```diff
@@ -481,13 +503,27 @@ static void emit_copy_stack_returns(AsmWriter &aw, size_t stack_return_size, siz
...
+      }
+      if (i + 2 <= stack_return_size) {
+        add_asm_line(aw, "movw "s + std::to_string(i) + "(%rsp), %r10w");
+        add_asm_line(aw, "movw %r10w, "s + std::to_string(i) + "(%rax)");
+        i += 2;
       }
+      if (i < stack_return_size) {
+        add_asm_line(aw, "movb "s + std::to_string(i) + "(%rsp), %r10b");
+        add_asm_line(aw, "movb %r10b, "s + std::to_string(i) + "(%rax)");
+      }
```
Comment (fw-immunant) [inline tools/rewriter/GenCallAsm.cpp:524]: If the other memcpy gets factored out into its own function this one probably should too.

File: tools/rewriter/GenCallAsm.cpp [hunk 6]
```diff
@@ -657,13 +707,13 @@ std::string emit_asm_wrapper(const CAbiSignature &sig,
     start_of_ret_space += 8;
 
     // See what unpadded alignment would be for the start of the stack return.
-    size_t unaligned = start_of_ret_space % stack_return_align;
+    size_t unaligned = (start_of_ret_space + stack_return_size) % stack_return_align;
```
Comment (fw-immunant) [inline tools/rewriter/GenCallAsm.cpp:710]: This comment doesn't seem to make sense anymore: the start of the stack return wouldn't include its size.

**Review by fw-immunant — COMMENTED** [review]
Various comments inline.

File: tools/rewriter/GenCallAsm.cpp [hunk 7]
```diff
@@ -11,18 +12,21 @@
...
 
 struct ParamLocation {
 private:
-  ParamLocation(const char *reg) : reg(reg) {}
+  ParamLocation(const char *reg, unsigned size, unsigned align) : reg(reg), _size(size), _align(align) {}
 
 public:
   const char *reg;
+  const unsigned _size;
+  const unsigned _align;
```
[the remark this answers is not in the document]
Comment (rinon) [reply tools/rewriter/GenCallAsm.cpp:24]: They were intended to be private, good catch.

File: tools/rewriter/DetermineAbi.cpp [hunk 8]
```diff
@@ -254,9 +252,11 @@ CAbiSignature determineAbi(const clang::CodeGen::CGFunctionInfo &info,
...
     // Replace the integer slots with an equal number of memory (stack) slots
     std::erase_if(sig.ret, is_integral);
-    for (int i = 0; i < num_regs; i++) {
-        sig.ret.push_back(CAbiArgKind::Memory);
-    }
+    sig.ret.push_back(CAbiArg{
+        .kind = CAbiArgKind::Memory,
+        .size = static_cast<unsigned>(num_regs) * 8,
+        .align = 8,
+    });
```
[the remark this answers is not in the document]
Comment (rinon) [reply tools/rewriter/DetermineAbi.cpp:259]: I believe branch only handles multiple integral values. Strangely sized structs are handled in `abiSlotsForArg` above.

File: tools/rewriter/GenCallAsm.cpp (hunk 2 above)
Comment (rinon) [reply tools/rewriter/GenCallAsm.cpp:425]: I originally thought we would copy the exact size, not a padded to 8 bytes size. I can revert this bit.

**Comment by rinon** [comment]
Somehow this bitrotted and is failing again now? I'm investigating.

File: tools/rewriter/GenCallAsm.cpp (hunk 2 above)
Comment (rinon) [reply tools/rewriter/GenCallAsm.cpp:425]: Reverted back to `pushq`s.

File: tools/rewriter/GenCallAsm.cpp (hunk 1 above)
Comment (rinon) [reply tools/rewriter/GenCallAsm.cpp:194]: It now copies the exact number of bytes.

File: tools/rewriter/GenCallAsm.cpp (hunk 4 above)
Comment (rinon) [reply tools/rewriter/GenCallAsm.cpp:476]: No, that's exactly what we're doing. `stack_arg_size` may not be a multiple of 8 now.

File: tools/rewriter/GenCallAsm.cpp (hunk 6 above)
Comment (rinon) [reply tools/rewriter/GenCallAsm.cpp:710]: Good point, this make more sense?

**Comment by rinon** [comment]
@fw-immunant I think I've addressed all your feedback, so this needs another look when you can.

File: tools/rewriter/GenCallAsm.cpp (hunk 4 above)
Comment (fw-immunant) [reply tools/rewriter/GenCallAsm.cpp:486]: I guess my question is: if `stack_arg_padding` is just `round_up(stack_arg_size, 8) - stack_arg_size`, why is it a separate argument? Or am I misunderstanding?

**Comment by fw-immunant** [comment]
> @fw-immunant I think I've addressed all your feedback, so this needs another look when you can.

One last question, otherwise all looks good.

File: tools/rewriter/GenCallAsm.cpp (hunk 4 above)
Comment (rinon) [reply tools/rewriter/GenCallAsm.cpp:486]: It doesn't need to be and I actually change this in https://github.com/immunant/IA2-Phase2/commit/3caefe7baa423b4796e6f466dfff8ee4b4ca07ee but that's not landed yet.

**Comment by rinon** [comment]
I ported over the free space simplification that is going to happen for ARM anyway. Should be good now?

**Review by fw-immunant — APPROVED** [review]
