### PR TITLE
 Run destructors with correct compartment pkey

### LINKED ISSUE #112: Run compartment destructors with compartment pkey
There is a crash after main in one of our tests that seems unrelated to pkey switching. This issue is for the second part of #95.

```
dmitriy@ubunut:~/git/IA2-Phase2$ gdb build/header-rewriter/tests/two_keys_minimal/two_keys_minimal-main
...
...
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fe0f2b in ?? () from /lib64/ld-linux-x86-64.so.2
(gdb) bt
#0  0x00007ffff7fe0f2b in ?? () from /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7db28d7 in __run_exit_handlers (status=0, listp=0x7ffff7f58718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true,
    run_dtors=run_dtors@entry=true) at exit.c:108
#2  0x00007ffff7db2a90 in __GI_exit (status=<optimized out>) at exit.c:139
#3  0x00007ffff7d900ba in __libc_start_main (main=0x55555555575c <main>, argc=2, argv=0x7fffffffe398, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe388) at ../csu/libc-start.c:342
#4  0x000055555555526e in _start ()
(gdb)
```

### PR DESCRIPTION
**Pull request by rinon**
Destructors for each library need to run with the relevant compartment's
pkey and stack in order to have access to the required memory. This
change adds a setup step that redirects the FINI and FINI_ARRAY dynamic
entries to our own shim that is wrapped and runs the relevant
constructors. Although this does not support wrapping destructors in an
unmodified external library (yet), that should also be possible with
this design.

Fixes #112

### CODE REVIEW

File: libia2/include/ia2_init.c [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+
+struct FinalizerInfo {
+  uint64_t fini_offset;
+  uint64_t fini_array_offset;
+  uint64_t fini_array_size;
+};
+
+/* Filled in by runtime initialization with contents of  .fini_array and
+ * .fini */
+static volatile struct FinalizerInfo finalizers
```
Comment (rinon) [inline libia2/include/ia2_init.c:55]: Needs to be made read-only

**Comment by rinon** [comment]
Finally passes CI! This is ready for review now.

File: libia2/main.c [hunk 2]
```diff
@@ -27,6 +27,15 @@ __attribute__((naked)) int __wrap_main(int argc, char **argv) {
       "call __real_main\n"
       // Restore the old stack pointer before returning.
       "mov main_sp(%%rip), %%rsp\n"
+      // Save return value
+      "mov %%rax,%%rbx\n"
```
Comment (ayrtonm) [inline libia2/main.c:31]: `__wrap_main` needs to preserve %rbx. Can't we use one of 'rdi, rsi, rdx, rcx, r8, r9, r10, r11' instead?

File: rewriter/tests/permissive_mode/permissive_mode.c [hunk 3]
```diff
@@ -8,6 +11,7 @@ INIT_RUNTIME(1);
 
 int main(int argc, char** argv) {
     char* buffer = NULL;
+#ifndef LIBIA2_INSECURE
```
Comment (ayrtonm) [inline rewriter/tests/permissive_mode/permissive_mode.c:14]: Weren't we removing insecure mode in another PR?

File: libia2/include/ia2_compartment_init.inc [hunk 4]
```diff
@@ -60,3 +65,135 @@ void COMPARTMENT_IDENT(init_tls)(void) {
...
+ * .fini */
+static volatile struct FinalizerInfo finalizers
+    __attribute__((__section__(".data.rel.ro.1"))) = {0};
+
+extern void COMPARTMENT_IDENT(__wrap_ia2_compartment_destructor)(void);
+
+__attribute__((no_sanitize("undefined"))) __attribute__((used)) void
+COMPARTMENT_IDENT(ia2_compartment_destructor)(void) {
+  static bool ran_destructors = false;
+  if (!&__ehdr_start || ran_destructors)
```
Comment (ayrtonm) [inline libia2/include/ia2_compartment_init.inc:88]: Is `!&__ehdr_start` valid or a malformed ELF (i.e. should we assert that it's true)?

File: libia2/include/ia2_compartment_init.inc [hunk 5]
```diff
@@ -60,3 +65,135 @@ void COMPARTMENT_IDENT(init_tls)(void) {
   };
   dl_iterate_phdr(protect_tls_pages, &args);
 }
+
+/* Magic symbol from the linker that marks the start of the ELF headers */
+extern Elf64_Ehdr __ehdr_start __attribute__((weak));
```
Comment (ayrtonm) [inline libia2/include/ia2_compartment_init.inc:70]: What compartments can write to `__ehdr_start`? I'm assuming it can't be relro since it's defined by the linker right?

File: libia2/include/ia2_compartment_init.inc [hunk 6]
```diff
@@ -60,3 +65,135 @@ void COMPARTMENT_IDENT(init_tls)(void) {
...
+    fprintf(stderr, "Failed to set relro section writable: %d\n", res);
+    exit(1);
+  }
+  for (int i = 0; i < dynamic_phdr->p_memsz / sizeof(Elf64_Dyn); i++) {
+    if (dynamic[i].d_tag == DT_FINI || dynamic[i].d_tag == DT_FINI_ARRAY ||
+        dynamic[i].d_tag == DT_FINI_ARRAYSZ) {
+      uintptr_t dynamic_entry_addr = (uintptr_t)&dynamic[i].d_un.d_val;
+      bool in_finalizers_mapping =
+          dynamic_entry_addr >= (uintptr_t)finalizers_region &&
+          dynamic_entry_addr + sizeof(Elf64_Xword) <=
```
Comment (ayrtonm) [inline libia2/include/ia2_compartment_init.inc:146]: This should be `<` since finalizers_region + region_size is on the next page

Comment (rinon) [reply libia2/include/ia2_compartment_init.inc:146]: I don't think so, `dynamic_entry_addr + sizeof(Elf64_Xword)` is the address of the next byte after the entry.

Comment (ayrtonm) [reply libia2/include/ia2_compartment_init.inc:147]: nit: Might be more obvious that it's the next byte if we use `&dynamic[i + 1]` like in the assert below.

**Comment by ayrtonm** [comment]
Just finished going through `ia2_setup_destructors`. There are some minor issues when accessing the union in `Elf64_Dyn`, but both variants have the same size so it's fine. The rest of the runtime and rewriter changes look good to me so I just need to go over the CMake changes.

File: cmake/define-test.cmake [hunk 7]
```diff
@@ -187,12 +188,18 @@ function(define_test)
...
     add_custom_command(
-        OUTPUT ${COPIED_SRCS} ${COPIED_HEADERS}
+        OUTPUT ${COPIED_SRCS}
         COMMAND cp ${ORIGINAL_SRCS} ${CMAKE_CURRENT_BINARY_DIR}/
-        COMMAND mkdir -p ${REWRITTEN_INCLUDE_DIR}
-        COMMAND cp ${ORIGINAL_HEADERS} ${REWRITTEN_INCLUDE_DIR}/
-        DEPENDS ${ORIGINAL_SRCS} ${ORIGINAL_HEADERS}
+        DEPENDS ${ORIGINAL_SRCS}
         WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
+    if (NOT ORIGINAL_HEADERS STREQUAL "")
```
Comment (ayrtonm) [inline cmake/define-test.cmake:195]: Aren't you setting `ORIGINAL_TARGETS` instead of `ORIGINAL_HEADERS` in the permissive mode test?

Comment (rinon) [reply cmake/define-test.cmake:195]: When calling `define_ia2_wrapper()`, yeah? It's just that this test doesn't have any headers and only a single compartment.

File: rewriter/SourceRewriter.cpp [hunk 8]
```diff
@@ -130,6 +131,13 @@ static bool ignore_file(const Filename &filename) {
   return !filename.starts_with(OutputDirectory) && !filename.starts_with(RootDirectory);
 }
 
+static bool ignore_function(const Filename &filename, const Function &function) {
```
Comment (ayrtonm) [inline rewriter/SourceRewriter.cpp:134]: Shouldn't be necessary with `--root-directory`.

**Review by ayrtonm — APPROVED** [review]
There's a minor nit in the rewriter changes but otherwise the new CMake stuff looks good to me.

File: rewriter/SourceRewriter.cpp (hunk 8 above)
Comment (rinon) [reply rewriter/SourceRewriter.cpp:134]: I want to specifically _include_ `ia2_compartment_destructor()`, which is outside the source directory, while still ignoring the rest of ia2.h and ia2_internal.h.
