### PR TITLE
Fix permissive mode to restore PKRU

### LINKED ISSUE #238: Permissive mode signal handler does not restore PKRU state after trapping
The permissive mode signal handler resets the PKRU register to 0 (all permitted) after a SIGSEGV PKRU fault, then is supposed to restore the PKRU register to the prior value after the faulting instruction executes. The restore isn't actually happening (at least not on my Ryzen 7).

The issue is that the kernel does not restore the PKRU from the extended fpstate unless the xsave header bit 9 is set to indicate that the PKRU state was saved in the xsave buffer. This bit is NOT set when the PKRU register is set to zero (its initial state) as an optimization to speed up the xsave operation. We need to explicitly set this bit of the feature mask if we want to change the value from zero to non-zero in the signal handler.

See the following kernel code where the PKRU state is restored from the signal context buffer:
https://github.com/torvalds/linux/blob/bfa3037d828050896ae52f6467b6ca2489ae6fb1/arch/x86/kernel/fpu/xstate.c#L1279-L1291

### PR DESCRIPTION
**Pull request by rinon**
Permissive mode had a few issues, most importantly:
- PKRU offset cpuid call was using the wrong register
- PKRU was not modified properly if it was 0 before the signal handler

The kernel only restores the PKRU value from the XSAVE area after the
signal handler if the PKRU bit in the XSAVE header is set (See Intel
manual Chapter 13.4 and linux kernel xstate.c). We want to change the
PKRU value after the permissive mode handler runs, so we need to make
sure this header bit is unconditionally set. If the PKRU value was 0,
the kernel will not set the bit before the signal handler runs.

Fixes #238

### CODE REVIEW

File: libia2/include/ia2.h [hunk 1]
```diff
@@ -36,6 +36,12 @@
 
 #endif
 
+static uint32_t ia2_get_pkey() {
+  uint32_t pkru;
+  __asm__("rdpkru" : "=a"(pkru) : "a"(0), "d"(0), "c"(0));
```
Comment (fw-immunant) [inline libia2/include/ia2.h:41]: I believe this has to be `__asm__` `volatile` because the pkru value comes out of "nowhere" as far as the optimizer is concerned--`rdpkru` is impure in that it doesn't compute an output from the listed inputs to the inline asm statement.

File: libia2/include/ia2.h [hunk 2]
```diff
@@ -36,6 +36,12 @@
 
 #endif
 
+static uint32_t ia2_get_pkey() {
```
Comment (fw-immunant) [inline libia2/include/ia2.h:39]: I would rather this were named `ia2_get_pkru`. The terminology convention we're following here is that there are 16 pkeys controlled by the one pkru register, and its value determines which set of pkeys the process has.

Comment (fw-immunant) [reply libia2/include/ia2.h:39]: We have several definitions of this as `rdpkru` in tests that should be changed to use this definition as a follow-up.

File: libia2/include/permissive_mode.h [hunk 3]
```diff
@@ -1,10 +1,27 @@
...
+
+/*
+ * PKRU is defined to be bit 9 in the XSAVE state component bitmap by the Intel
+ * manual.
+ */
+#define XFEATURE_PKRU 9
+#define XFEATURE_MASK_PKRU		(1 << XFEATURE_PKRU)
+
+/* Offset of the XSAVE header in bytes from the XSAVE area base */
+#define XSAVE_HEADER_OFFSET 512
```
Comment (fw-immunant) [inline libia2/include/permissive_mode.h:24]: Where does this constant come from? The Intel [Software Developers Manual](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-vol-1-manual.pdf) says the offset used in has to be looked up via cpuid (§13.4.3):
> As noted in Section 13.2, CPUID.(EAX=0DH,ECX=9):EBX enumerates the offset (in bytes, from the base of the
XSAVE area) of the section of the extended region of the XSAVE area used for PKRU state (when the standard
format of the extended region is used).

The alternative to the standard format is the compacted format, which requires adding up sizes for the saved components, and which I'm guessing isn't enabled/relevant here.

**Review by fw-immunant — COMMENTED** [review]
A few nits, the important two are volatile and documenting the xsave offset stuff.

File: libia2/test/CMakeLists.txt [hunk 4]
```diff
@@ -0,0 +1,5 @@
+add_executable(permissive_mode_test permissive_mode.c)
+target_link_libraries(permissive_mode_test libia2)
```
Comment (fw-immunant) [inline libia2/test/CMakeLists.txt:2]: Test failures on ubuntu say we need libdl here too.

Is there a reason not to use our `define_test` infrastructure? It includes things like making sure our padded libc is used and propagating the build-system `LIBIA2_INSECURE` into the C preprocessor `LIBIA2_INSECURE`.

File: libia2/test/permissive_mode.c [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+
+    buffer = mmap(NULL, 4096, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON, -1, 0);
+
+    pkey_mprotect(buffer, 4096, PROT_READ | PROT_WRITE, 1);
+    buffer[0] = 'a';
+
+    pkey_mprotect(buffer, 4096, PROT_READ | PROT_WRITE, 2);
+    buffer[0] = 'b';
+
+    assert(ia2_get_pkey() == 0xFFFFFFF0);
```
Comment (fw-immunant) [inline libia2/test/permissive_mode.c:23]: These assertions and `pkey_mprotect`s will fail in insecure mode. Probably all of this can just be wrapped in `#ifndef LIBIA2_INSECURE`.

File: libia2/include/ia2.h (hunk 1 above)
Comment (fw-immunant) [reply libia2/include/ia2.h:41]: To support insecure mode, this should be `IA2_RDPKRU` rather than `"rdplru"` and initialize `pkru` to zero.

Comment (rinon) [reply libia2/include/ia2.h:41]: We use an output, so we don't need volatile in this particular case. The compiler won't be able to discard this assembly statement because it needs the `pkru` output variable. The only time we _need_ volatile is if the assembly has side-effects not declared as outputs. So a wrpkru probably needs volatile, but reading doesn't.

File: libia2/include/permissive_mode.h (hunk 3 above)
Comment (rinon) [reply libia2/include/permissive_mode.h:24]: This is not the PKRU offset (which we look up from cpuid). This is the offset of the XSAVE header which is always 512 bytes in.

> The XSAVE header of an XSAVE area comprises the 64 bytes starting at offset 512 from the area’s base address:
 Bytes 7:0 of the XSAVE header is a state-component bitmap (see Section 13.1) called XSTATE_BV. It
identifies the state components in the XSAVE area.

The compacted format is never used for the signal handler context here, fortunately. We could and maybe should check the relevant bit of the header to ensure this but :man_shrugging:.

File: libia2/include/ia2.h (hunk 1 above)
Comment (fw-immunant) [reply libia2/include/ia2.h:41]: The concern isn't the compiler removing it entirely, but reordering it with respect to other operations because it considers it to be "pure". For example, it could hoist it above somewhere that we write the PKRU, even if the write is considered side-effecting, because the compiler doesn't know that the write and read are linked through the PKRU.

File: libia2/include/permissive_mode.h (hunk 3 above)
Comment (fw-immunant) [reply libia2/include/permissive_mode.h:24]: Ah, I very much had the wrong context in mind here. This is fine then, though it would be nice to point to the docs where this comes from (Intel manual §13.4.2).

File: libia2/test/CMakeLists.txt (hunk 4 above)
Comment (rinon) [reply libia2/test/CMakeLists.txt:2]: I didn't want to actually run the rewriter or wrap anything. TBH I don't know how that macro works anymore and I didn't feel like figuring it out.

File: libia2/test/permissive_mode.c (hunk 5 above)
Comment (rinon) [reply libia2/test/permissive_mode.c:23]: The test makes no sense to run in insecure mode, so I'll just disable the whole test.

**Review by fw-immunant — APPROVED** [review]
Looks good now. I'll follow-up to make the rdpkru wrapper work for insecure mode and use it in other tests.
